### ISSUE TITLE
Issue importing deps

### ISSUE THREAD

**Issue by moonstripe** [drashland/website-v2#182]
Please alter the docs to reflect the import_map.json standard for fresh: https://fresh.deno.dev/docs/introduction

**Comment by crookse** [comment]
hey @moonstripe, could you explain more in depth what the issue is and for what module (eg, drash, sinco, etc). im not sure what's being requested. thanks!

**Comment by crookse** [comment]
hey @moonstripe , i'm going to close this for now. feel free to respond though. we have notifications in Discord and we can respond back quick.

**Comment by moonstripe** [comment]
sorry about that, haven't gotten the time to clarify, ill check out discord!

feel free to keep it closed
