### ISSUE TITLE
[Drash] Add tree-shaking information page

### ISSUE THREAD

**Issue by crookse** [drashland/website-v2#34]
## Summary

What:

There are many ways to import Drash:

```typescript
import * as Drash from ".../drash/mod.ts";
import { Something } from ".../drash/mod.ts";
import Something from ".../drash/src/http/something.ts";
```

Each import method will have a different dependency tree. We should inform users about the different ways to import Drash so they can be informed on the size of their dependency tree.

Why:

Importing a dependency and not using it is a waste of space. Informing users how they can keep their applications small would be a nice addition to the docs.

**Comment by ebebbington** [comment]
honestly @crookse im not sure how useful this would be, i get the reasoning, but:

- someone using drash will need to import at least 1 thing from every file we have (excl services)

So no matter how they import what they need, they'll end up with the same tree regardless of how they do it

Whereas this would be great for something like Nessie, where if you're using postgres, you'll only want to import the client from `src/postgres/postgres.ts` ibstead of `mod.ts` (which includes mysql, postgres and sqlite)

**Comment by crookse** [comment]
@ebebbington true. closing
