### ISSUE TITLE
Drash: Add new section for recommended services to use

### ISSUE THREAD

**Issue by ebebbington** [drashland/website-v2#37]
eg 

## Here are the list of recommend services we believe would be great for you to use

1. Paladin: why
2. Response time: why

Here is an example of how your server file may look

```ts
import { all da services }

const paladin = new paladin()
```

**Comment by ebebbington** [comment]
@crookse wdyt?

**Comment by crookse** [comment]
sounds good to me

**Comment by ebebbington** [comment]
wil do this sunday, today for me, tomorrow for you 🤯
