### ISSUE TITLE
sinco: mention using firefox, will close your main browser

### ISSUE THREAD

**Issue by ebebbington** [drashland/website-v2#72]
when using firefox as the driver, if you have your usual browser open that you use for youtube or stackoverflow, the `.done()` method will close it

**Comment by ebebbington** [comment]
there's nothing we can do about it, and i dont know why it happened in v3, nothing was changed by us to do this

Not too bad, because sinco is aimed to be used in CI i guess

**Comment by SnoCold** [comment]
This is now mentioned in docs/sinco/v4.x/2_tutorials/2_client/4_closing_the_client.md for Sinco v4 in #88

**Comment by ebebbington** [comment]
closing
