### ISSUE TITLE
Markdown issues on dmm

### ISSUE THREAD

**Issue by ebebbington** [drashland/website-v2#73]
## Summary

A clear and concise summary of the bug.

## Steps To Reproduce The Bug

1. These ...
2. Steps ...
3. Are ...
4. Required ...

## Suggested Solution(s)

A list of suggested solutions to try/implement.

## Additional Context

Add any other context that will help the project maintainers investigate this issue.

**Comment by ebebbington** [comment]
uhhh i dont see any problems

**Comment by ebebbington** [comment]
The screenshot we had was

![image](https://user-images.githubusercontent.com/47337480/146298724-660e24da-ccd2-4d6c-aa12-395f352ac47e.png)

**Comment by crookse** [comment]
im not seeing this issue either

**Comment by ebebbington** [comment]
Have asked Bubbles (whom mentioned it to me) to check again

**Comment by MierenManz** [comment]
Hi Bubbles here.
Checked it again and now there is a scrollbar under that tab so it seems like it works now.
Also the lightmode bug has also been fixed. Seems weird that I only experienced them yesterday but now it's fine. Prob

**Comment by MierenManz** [comment]
![Uploading image.png…]()
This is what it is now for me. As a reference

**Comment by ebebbington** [comment]
@MierenManz thanks that’s greatly appreciated, yeah not sure why/how you saw it but good to know it isn’t a problem anymore, will close this issue then
